name: Build HasFlagExtension

on:
  push:
    paths:
      - 'Metriks/**'
      - 'Metriks.Test/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest 

    env:
      Solution_Name: Metriks.sln
      Test_Project_Path: Metriks.Test\Metriks.Test.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build Projects
      run: dotnet build

    - name: Execute unit tests
      run: dotnet test --no-restore

    - name: Restore the application
      run: dotnet restore
      
